# Generated by Django 5.2 on 2025-05-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('partido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('valor', models.IntegerField()),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='tasks.pregunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'db_table': 'alternativa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(help_text='Formato: 12.345.678-K o sin puntos', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.PROTECT, to='tasks.sexo')),
                ('ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.PROTECT, to='tasks.ubicacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternativa', models.ForeignKey(db_column='id_alternativa', on_delete=django.db.models.deletion.CASCADE, to='tasks.alternativa')),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='tasks.pregunta')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuario',
                'db_table': 'respuesta_usuario',
                'unique_together': {('usuario', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='Afinidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField()),
                ('candidato', models.ForeignKey(db_column='id_candidato', on_delete=django.db.models.deletion.CASCADE, to='tasks.candidato')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'verbose_name': 'Afinidad',
                'verbose_name_plural': 'Afinidades',
                'db_table': 'afinidad',
                'unique_together': {('usuario', 'candidato')},
            },
        ),
    ]
