# Generated by Django 5.2 on 2025-05-14 05:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_candidato_pregunta_sexo_ubicacion_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("O'Higgins", "O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], default='Metropolitana de Santiago', max_length=50, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='afinidad',
            name='usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AlterField(
            model_name='respuestausuario',
            name='usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='descripcion',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, unique=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='region',
            field=models.CharField(max_length=100, unique=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Ej: 12.345.678-5 o 12345678-5', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
