# Generated by Django 5.1.3 on 2025-05-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_usuario_ubicacion_usuario_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='tasks.alternativa')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='tasks.candidato')),
            ],
            options={
                'verbose_name': 'Ponderación',
                'verbose_name_plural': 'Ponderaciones',
                'db_table': 'ponderacion',
                'unique_together': {('alternativa', 'candidato')},
            },
        ),
    ]
