# Generated by Django 5.2.1 on 2025-06-17 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_ponderacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Debe ingresarse SIN puntos y CON guión: 12345678-5', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT'),
        ),
    ]
